**이름: 손민아** 20211231

In [67]:
import numpy as np

## 1. 0 부터 8까지의 값을 순차적으로 갖는 3x3 행렬을 생성하시오

In [73]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## 2.  i번째 열은 원소값으로 모두 (i-1)을 갖는 5x5 행렬을 생성하시오.

In [74]:
z = np.zeros((5,5))
z += np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [75]:
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

## 3. integer(32 bit) ndarray를 float(32 bit) ndarray로 바꾸려면 어떻게 해야하는가?

In [76]:
z = np.arange(10, dtype=np.int32)

In [78]:
z_new = z.astype('float32')
print(z_new)
z

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 4. quest.pickle 파일에는 5점 만점으로 된 설문조사 결과가 배열로 저장되어 있다. 이 파일을 읽어와서 설문조사 결과 5점 초과하는 값이 있는지 살펴보고 있을 경우 모두 5로 변경하여라.

In [69]:
with open('../data/quest.pickle','rb') as f:
    quest = np.load('../data/quest.pickle', allow_pickle=True)

In [70]:
quest

array([[1, 2, 1, 2, 2],
       [1, 3, 2, 3, 2],
       [1, 4, 3, 3, 3],
       [2, 5, 4, 4, 4],
       [2, 5, 6, 2, 5],
       [3, 6, 4, 2, 5],
       [3, 5, 4, 1, 6],
       [3, 5, 5, 1, 3]], dtype=int64)

In [71]:
quest[np.where(quest>5)]
quest_new = np.where(quest > 5, 5, quest)
quest_new

array([[1, 2, 1, 2, 2],
       [1, 3, 2, 3, 2],
       [1, 4, 3, 3, 3],
       [2, 5, 4, 4, 4],
       [2, 5, 5, 2, 5],
       [3, 5, 4, 2, 5],
       [3, 5, 4, 1, 5],
       [3, 5, 5, 1, 3]], dtype=int64)

In [72]:
print(quest_new)

[[1 2 1 2 2]
 [1 3 2 3 2]
 [1 4 3 3 3]
 [2 5 4 4 4]
 [2 5 5 2 5]
 [3 5 4 2 5]
 [3 5 4 1 5]
 [3 5 5 1 3]]